# Generated by Django 4.2.27 on 2025-12-23 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique certificate identifier for verification', unique=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF certificate', null=True, upload_to='certificates/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='articles.article')),
                ('revoked_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['certificate_id'], name='certificate_certifi_a0a669_idx'), models.Index(fields=['status'], name='certificate_status_a01db5_idx'), models.Index(fields=['article'], name='certificate_article_13028f_idx')],
            },
        ),
    ]
