# Generated by Django 4.2.27 on 2025-12-23 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(help_text='Unique submission identifier', max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('authors', models.JSONField(default=list, help_text='List of authors with affiliations')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('DESK_CHECK', 'DESK_CHECK'), ('REVIEWERS_INVITED', 'REVIEWERS_INVITED'), ('UNDER_REVIEW', 'UNDER_REVIEW'), ('REVISION_REQUIRED', 'REVISION_REQUIRED'), ('REVISED_SUBMITTED', 'REVISED_SUBMITTED'), ('EDITOR_DECISION', 'EDITOR_DECISION'), ('ACCEPTED', 'ACCEPTED'), ('PAYMENT_PENDING', 'PAYMENT_PENDING'), ('PAID', 'PAID'), ('PRODUCTION', 'PRODUCTION'), ('SCHEDULED', 'SCHEDULED'), ('PUBLISHED', 'PUBLISHED'), ('CERTIFICATE_ISSUED', 'CERTIFICATE_ISSUED'), ('REJECTED', 'REJECTED'), ('ARCHIVED', 'ARCHIVED')], default='DRAFT', max_length=30)),
                ('ethics_declaration', models.BooleanField(default=False)),
                ('originality_declaration', models.BooleanField(default=False)),
                ('publication_url', models.URLField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('corresponding_author', models.ForeignKey(limit_choices_to={'role': 'AUTHOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='journals.journal')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('ACCEPT', 'Accept'), ('REVISE', 'Revise'), ('REJECT', 'Reject')], max_length=20)),
                ('comments_to_author', models.TextField(help_text='Comments visible to the author')),
                ('confidential_comments', models.TextField(blank=True, help_text='Confidential comments (not visible to author)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.article')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'REVIEWER'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'unique_together': {('article', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('manuscript_file', models.FileField(help_text='Manuscript file (PDF/DOCX)', upload_to='articles/manuscripts/')),
                ('revision_type', models.CharField(choices=[('INITIAL', 'Initial Submission'), ('MINOR', 'Minor Revision'), ('MAJOR', 'Major Revision')], default='INITIAL', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Author notes for this revision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='articles.article')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_versions',
                'ordering': ['-version_number'],
                'unique_together': {('article', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['submission_id'], name='articles_submiss_610345_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='articles_status_a4f178_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['corresponding_author', 'status'], name='articles_corresp_0e944c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['journal', 'status'], name='articles_journal_a78b76_idx'),
        ),
    ]
