# Generated by Django 4.2.27 on 2025-12-23 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('REVIEW_SUBMITTED', 'Review Submitted'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('CERTIFICATE_ISSUED', 'Certificate Issued'), ('CERTIFICATE_REVOKED', 'Certificate Revoked'), ('ADMIN_OVERRIDE', 'Admin Override'), ('ARTICLE_SUBMITTED', 'Article Submitted'), ('ARTICLE_PUBLISHED', 'Article Published')], max_length=50)),
                ('entity_type', models.CharField(help_text='Type of entity (ARTICLE, INVOICE, CERTIFICATE, etc.)', max_length=50)),
                ('entity_id', models.PositiveIntegerField(help_text='ID of the entity')),
                ('metadata', models.JSONField(default=dict, help_text='Additional action metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor'], name='audit_logs_actor_i_0badd2_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx')],
            },
        ),
    ]
