# Generated by Django 4.2.27 on 2025-12-23 04:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('issn', models.CharField(blank=True, max_length=20, unique=True)),
                ('scope', models.TextField(help_text='Journal scope and description')),
                ('apc_enabled', models.BooleanField(default=True, help_text='Whether APC payment is required for this journal')),
                ('apc_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Article Processing Charge amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, UZS)', max_length=3)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='journals/logos/')),
                ('publication_base_url', models.URLField(blank=True, help_text='Base URL for published articles (optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'journals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerJournalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_assignments', to='journals.journal')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'REVIEWER'}, on_delete=django.db.models.deletion.CASCADE, related_name='journal_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviewer_journal_assignments',
                'unique_together': {('reviewer', 'journal')},
            },
        ),
    ]
